name: Acceptance Test

on:
  push:
    branches: [main, Acceptance-Test]
  pull_request:
    branches: [main, Acceptance-Test]

jobs:
  acceptance-test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:18
        ports:
          - 3000:3000
        options: >-
          --privileged
          --health-cmd "curl --fail https://assessything.up.railway.app/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          NODE_ENV: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &  # Start the app in the background

    - name: Wait for app to start
      run: |
        until curl --silent --fail https://assessything.up.railway.app/; do
          echo "Waiting for app to start..."
          sleep 5
        done

    - name: Run acceptance tests
      run: npm test -- test/acceptance-test.mjs  # Run the acceptance test
