name: Acceptance Tests

on:
  push:
    branches:
    - 'main'
    - 'Acceptance-Tests'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16